# -*- coding: utf-8 -*-
# Part of Rhodes Technologies.
{
    "name": "Afrex Supply Chain",
    "author": "Khalid Joomun (Rhodes Technologies Ltd)",
    "website": "https://www.rhodes.mu",
    "support": "erp@rhodes.mu",
    "category": "Tools",
    "description": """Afrex Supply Chain""",
    "version": "1.0.1",
    "depends": ["mail",
                "contacts",
                "calendar",
                "product",
                "stock",
                "purchase_stock",
                "sale_management",
                "purchase",
                "crm",
                "portal",
                "amount_in_words_invoice",
                "instant_attachment_preview",
                "kg_hide_menu",
                "muk_web_theme",
                "muk_product",],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        'data/data.xml',
        'data/asc_sequence.xml',
        # 'data/asc_port_data.xml',
        'data/asc_product_packaging_data.xml',
        'data/asc_document_type_data.xml',
        'data/asc_shipping_line_data.xml',
        'data/asc_container_type_data.xml',
        # "data/ir_cron_data.xml",
        # "data/mail_template.xml",
        "report/rfq_template_inherit.xml",
        "report/quotation_template_inherit.xml",
        "report/asc_quote_request_template.xml",
        "report/asc_purchase_order_template.xml",
        "report/asc_shipping_instructions_template.xml",
        "report/asc_quotation_template.xml",
        "report/asc_proforma_invoice_template.xml",
        "report/asc_commercial_invoice_template.xml",
        "report/asc_credit_note_template.xml",
        "report/asc_packing_list_template.xml",
        "report/asc_origin_certificate_template.xml",
        "report/asc_payment_request_template.xml",
        "report/asc_profit_estimate_template.xml",
        "report/asc_profit_estimate_new_template.xml",
        "report/address_layout_inherit.xml",
        "report/asc_paper_format.xml",
        "report/asc_report.xml",
        "views/res_company_view_inherit.xml",
        "views/res_config_settings_view_inherit.xml",
        "views/res_partner_view_inherit.xml",
        "views/res_bank_view_inherit.xml",
        "views/res_partner_bank_view_inherit.xml",
        "views/product_template_view_inherit.xml",
        "views/purchase_order_view_inherit.xml",
        "views/sale_order_view_inherit.xml",
        "views/account_move_view_inherit.xml",
        "views/account_payment_term_view_inherit.xml",
        "views/stock_picking_view_inherit.xml",
        "views/crm_lead_view_inherit.xml",
        "views/asc_product_combination_views.xml",
        "views/asc_packaging_views.xml",
        "views/asc_port_views.xml",
        "views/asc_shipping_line_views.xml",
        "views/asc_specification_views.xml",
        "views/asc_document_views.xml",
        "views/asc_document_type_views.xml",
        "views/asc_payment_request_views.xml",
        "views/menu.xml",
        "wizard/asc_product_selection_view.xml",
        "wizard/asc_generate_purchase_order_view.xml",
        "wizard/asc_generate_sale_order_view.xml",
        "wizard/asc_generate_proforma_view.xml",
        "wizard/asc_confirm_invoice_view.xml",
        "wizard/asc_supplier_invoice_view.xml",
        "wizard/asc_generate_payment_request_view.xml",
        "wizard/asc_set_document_view.xml",
        "wizard/asc_update_packaging_view.xml",
        "wizard/asc_update_sale_order_view.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'afrex_supply_chain/static/css/accordion-custom.css',
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
